### ISSUE TITLE
2to3 branch GUI problem

### ISSUE THREAD

**Issue by MonsieurNicolas** [kenmcmil/ivy#17]
It looks like exploring nodes in the GUI just throws an error.

For example, when reviewing a model that has problems with `diagnose=true`, and clicking on any node yields:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 720, in getboolean
    return self.tk.getboolean(s)
_tkinter.TclError: expected boolean value but got "??"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1882, in __call__
    args = self.subst(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1569, in _substitute
    try: e.focus = getboolean(f)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 722, in getboolean
    raise ValueError("invalid literal for getboolean()")
ValueError: invalid literal for getboolean()
```

I got this error with the model from the tutorial, and clicking on any `client`:

```
#lang ivy1.7

type client
type server

relation link(X:client, Y:server)
relation semaphore(X:server)

after init {
    semaphore(W) := true;
    link(X,Y) := false
}

action connect(x:client,y:server) = {
  require semaphore(y);
  link(x,y) := true;
  semaphore(y) := false
}

action disconnect(x:client,y:server) = {
  require link(x,y);
  link(x,y) := false;
  semaphore(y) := true
}

private {
#invariant [server_tracks] link(C, S) -> semaphore(S) = false
}

export connect
export disconnect

invariant [no_dupe] link(C1, S) & link(C2, S) -> C1 = C2
```

**Comment by graydon** [comment]
I've found the root cause of this and a credible monkeypatch-fix, will attempt a better/proper one tomorrow (might involve feeding fixes upstream -- python changed their tkinter module)

**Comment by osankur** [comment]
Hi,
I have the exact same issue with the latest commit on the master branch with Python 3.10.12. Has there been any progress on this or am I doing something wrong?
