### ISSUE TITLE
AttributeError: 'IsolateDef' object has no attribute 'create_isolate'

### ISSUE THREAD

**Issue by ArneVogel** [kenmcmil/ivy#44]
I get the above error when trying to use ivy following the instructions at: http://microsoft.github.io/ivy/install.html

Command to trigger the error `ivy doc/examples/client_server_example.ivy`

The error occurs both when installing from source or installing the binary with pip; both on ubuntu 20.04 and an arch based system. 

Full output below

```
Traceback (most recent call last):
  File "/usr/bin/ivy", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/ivy/ivy.py", line 14, in main
    ui_main_loop(ivy_init())
  File "/usr/lib/python2.7/site-packages/ivy/ivy_init.py", line 106, in ivy_init
    source_file(fn,f,**skwargs)
  File "/usr/lib/python2.7/site-packages/ivy/ivy_init.py", line 72, in source_file
    ivy_load_file(f,**kwargs)
  File "/usr/lib/python2.7/site-packages/ivy/ivy_compiler.py", line 2301, in ivy_load_file
    ivy_compile(decls,**kwargs)
  File "/usr/lib/python2.7/site-packages/ivy/ivy_compiler.py", line 2239, in ivy_compile
    iso.create_isolate(isolate.get(),mod,**kwargs)
AttributeError: 'IsolateDef' object has no attribute 'create_isolate'
```

**Comment by nano-o** [comment]
You could try one of the docker setups here if you're having trouble running Ivy: https://github.com/nano-o/ivy-docker

**Comment by ArneVogel** [comment]
> You could try one of the docker setups here if you're having trouble running Ivy: https://github.com/nano-o/ivy-docker

thanks

---

Also an update to the report: `ivy_check` and `ivy_to_cpp` seem to work fine. It's just the `ivy` command that seems to be broken for me.

**Comment by nano-o** [comment]
Ah okay, I didn't get that. I never use the `ivy` command and I'm not sure what it's supposed to do.

**Comment by kape1395** [comment]
The same problem with the `ivy` command here.

**Comment by TonyZhangND** [comment]
Same issue experienced on both OSX and Ubuntu

**Comment by NamrathaG** [comment]
Same issue on Windows

**Comment by VSEJGFB** [comment]
Same issue on Ubuntu.

**Comment by mgritter** [comment]
The issue is that `iso` is used as a variable in this function, shadowing the alias used to import the `ivy_isolate` module.  My PR renames the variable and allows the program to start normally.
